<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DTOs\" />
    <Folder Include="Interfaces\Repositories\" />
    <Folder Include="Interfaces\Services\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlyzenApi.Domain\FlyzenApi.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="8.0.10" />
  </ItemGroup>

</Project>
